project:
  type: website

execute: 
  freeze: auto
  
website:
  announcement:
    icon: cone-striped
    dismissable: true
    content: |
      "Vous lisez une version non finalisée d'un blog actuellement en cours d'élaboration"
    type: primary
    position: below-navbar
  title: "dive-R-city"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/

format:
  html:
    theme: cosmo
    css: styles.css



