project:
  type: website

website:
  announcement:
    icon: cone-striped
    dismissable: false
    content: |
      "Vous lisez une version non finalisée d'un blog actuellement en cours d'élaboration"
    type: primary
    position: below-navbar
  title: "dive-R-city"
  description: "A part of me" 
  navbar:
    title: "A lambda"
    right:
      - text: About
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/

format:
  html:
    lang: fr
    date-format: 'dddd[, ] Do MMMM YYYY'
    code-link: true
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

execute: 
  freeze: false