name: GA_tests

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  ListFilesJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world!"
    
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        
      - name: List files in repository
        run: |
          echo "The repository ${{ github.repository }} containts the following files:"
          tree && df -h
